apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  namespace: bankapp-namespace
  labels:
    app: bankapp-deploy
spec:
  type: ClusterIP # Ingress with target-type: ip routes directly to Pod IPs
  selector:
    app: bankapp-deploy # Correctly matches your running pods!
  ports:
    - protocol: TCP
      port: 8080       # Port exposed to Ingress
      targetPort: 8080 # Port your Spring Boot / app container runs on
